package com.proxiad.extranet.core.model.client;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * The Client entity will serve to keep information about the clients of the company
 * 
 * @author Mihail Merkov
 */
@Entity
@Table(name = "CLIENT")
public class Client {
	
	@Id
	@Column(name = "ID_CLIENT")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "NAME")
	private String name;
	
	@Column(name = "CODE_CEGID_1")
	private String codeCEGID1;
	
	@Column(name = "CODE_CEGID_2")
	private String codeCEGID2;
	
	@Column(name = "CODE_CEGID_3")
	private String codeCEGID3;
	
	@Column(name = "ACTIVE", nullable = false)
	private boolean active;
	
	@Column(name = "SPECIAL", nullable = false)
	private boolean special;
	
	@Column(name = "SERVICE_CENTER", nullable = false)
	private boolean serviceCenter;
	
	@Column(name = "GENERATE_CRA", nullable = false)
	private boolean generateCra;
	
	/**
	 * Get the id of the entity
	 * @return {@link Long}
	 */
	public Long getId() {
		return id;
	}
	
	/**
	 * Set the id of the entity
	 * @param id {@link Long}
	 */
	public void setId(final Long id) {
		this.id = id;
	}
	
	/**
	 * Get name of the client
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * Set name of the client
	 * @param name {@link String}
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Get special code, which belongs to the client
	 * @return {@link String}
	 */
	public String getCodeCEGID1() {
		return codeCEGID1;
	}
	
	/**
	 * Set special code, which belongs to the client
	 * @param codeCEGID1 {@link String}
	 */
	public void setCodeCEGID1(final String codeCEGID1) {
		this.codeCEGID1 = codeCEGID1;
	}
	
	/**
	 * Get special code, which belongs to the client
	 * @return {@link String}
	 */
	public String getCodeCEGID2() {
		return codeCEGID2;
	}
	
	/**
	 * Set special code, which belongs to the client
	 * @param codeCEGID1 {@link String}
	 */
	public void setCodeCEGID2(final String codeCEGID2) {
		this.codeCEGID2 = codeCEGID2;
	}
	
	/**
	 * Get special code, which belongs to the client
	 * @return {@link String}
	 */
	public String getCodeCEGID3() {
		return codeCEGID3;
	}

	/**
	 * Set special code, which belongs to the client
	 * @param codeCEGID1 {@link String}
	 */
	public void setCodeCEGID3(final String codeCEGID3) {
		this.codeCEGID3 = codeCEGID3;
	}
	
	/**
	 * Flag which indicate, whether the client is active or not
	 * @return boolean
	 */
	public boolean isActive() {
		return active;
	}
	
	/**
	 * Set whether the client is active or not
	 * @param active boolean
	 */
	public void setActive(boolean active) {
		this.active = active;
	}
	
	/**
	 * Flag which indicate whether the client is special or not
	 * @return boolean
	 */
	public boolean isSpecial() {
		return special;
	}
	
	/**
	 * Set whether the client is special or not
	 * @param special boolean
	 */
	public void setSpecial(boolean special) {
		this.special = special;
	}
	
	/**
	 * Flash which indicate whether the client is handle by the service center or not
	 * @return boolean
	 */
	public boolean isServiceCenter() {
		return serviceCenter;
	}
	
	/**
	 * Set whether the client is handle by the service center or not
	 * @param serviceCenter boolean
	 */
	public void setServiceCenter(boolean serviceCenter) {
		this.serviceCenter = serviceCenter;
	}
	
	/**
	 * Flag which indicate whether the client should be generated by CRA process or not
	 * @return boolean
	 */
	public boolean isGenerateCra() {
		return generateCra;
	}
	
	/**
	 * Set whether the client should be generated by CRA process or not
	 * @param generateCra
	 */
	public void setGenerateCra(boolean generateCra) {
		this.generateCra = generateCra;
	}
}
